const data = {
  location: {
    name: "Pune",
    region: "Maharashtra",
    country: "India",
    lat: 18.53,
    lon: 73.87,
    tz_id: "Asia/Kolkata",
    localtime_epoch: 1679061362,
    localtime: "2023-03-17 19:26",
  },
  current: {
    last_updated_epoch: 1679060700,
    last_updated: "2023-03-17 19:15",
    temp_c: 25.4,
    temp_f: 77.7,
    is_day: 0,
    condition: {
      text: "Clear",
      icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
      code: 1000,
    },
    wind_mph: 11.0,
    wind_kph: 17.6,
    wind_degree: 301,
    wind_dir: "WNW",
    pressure_mb: 1010.0,
    pressure_in: 29.83,
    precip_mm: 0.0,
    precip_in: 0.0,
    humidity: 55,
    cloud: 14,
    feelslike_c: 26.3,
    feelslike_f: 79.3,
    vis_km: 10.0,
    vis_miles: 6.0,
    uv: 1.0,
    gust_mph: 12.5,
    gust_kph: 20.2,
  },
  forecast: {
    forecastday: [
      {
        date: "2023-03-17",
        date_epoch: 1679011200,
        day: {
          maxtemp_c: 31.9,
          maxtemp_f: 89.4,
          mintemp_c: 20.2,
          mintemp_f: 68.4,
          avgtemp_c: 25.0,
          avgtemp_f: 77.0,
          maxwind_mph: 9.2,
          maxwind_kph: 14.8,
          totalprecip_mm: 0.1,
          totalprecip_in: 0.0,
          totalsnow_cm: 0.0,
          avgvis_km: 10.0,
          avgvis_miles: 6.0,
          avghumidity: 53.0,
          daily_will_it_rain: 0,
          daily_chance_of_rain: 0,
          daily_will_it_snow: 0,
          daily_chance_of_snow: 0,
          condition: {
            text: "Sunny",
            icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
            code: 1000,
          },
          uv: 6.0,
        },
        astro: {
          sunrise: "06:41 AM",
          sunset: "06:45 PM",
          moonrise: "03:07 AM",
          moonset: "02:16 PM",
          moon_phase: "Waning Crescent",
          moon_illumination: "29",
          is_moon_up: 1,
          is_sun_up: 0,
        },
        hour: [
          {
            time_epoch: 1678991400,
            time: "2023-03-17 00:00",
            temp_c: 21.6,
            temp_f: 70.9,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 2.0,
            wind_kph: 3.2,
            wind_degree: 66,
            wind_dir: "ENE",
            pressure_mb: 1013.0,
            pressure_in: 29.91,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 67,
            cloud: 5,
            feelslike_c: 21.6,
            feelslike_f: 70.9,
            windchill_c: 21.6,
            windchill_f: 70.9,
            heatindex_c: 24.5,
            heatindex_f: 76.1,
            dewpoint_c: 15.2,
            dewpoint_f: 59.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 2.9,
            gust_kph: 4.7,
            uv: 1.0,
          },
          {
            time_epoch: 1678995000,
            time: "2023-03-17 01:00",
            temp_c: 21.2,
            temp_f: 70.2,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 2.0,
            wind_kph: 3.2,
            wind_degree: 66,
            wind_dir: "ENE",
            pressure_mb: 1012.0,
            pressure_in: 29.89,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 68,
            cloud: 5,
            feelslike_c: 21.2,
            feelslike_f: 70.2,
            windchill_c: 21.2,
            windchill_f: 70.2,
            heatindex_c: 24.4,
            heatindex_f: 75.9,
            dewpoint_c: 15.1,
            dewpoint_f: 59.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 2.9,
            gust_kph: 4.7,
            uv: 1.0,
          },
          {
            time_epoch: 1678998600,
            time: "2023-03-17 02:00",
            temp_c: 20.7,
            temp_f: 69.3,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 2.5,
            wind_kph: 4.0,
            wind_degree: 93,
            wind_dir: "E",
            pressure_mb: 1012.0,
            pressure_in: 29.88,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 72,
            cloud: 7,
            feelslike_c: 20.7,
            feelslike_f: 69.3,
            windchill_c: 20.7,
            windchill_f: 69.3,
            heatindex_c: 20.7,
            heatindex_f: 69.3,
            dewpoint_c: 15.4,
            dewpoint_f: 59.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 3.6,
            gust_kph: 5.8,
            uv: 1.0,
          },
          {
            time_epoch: 1679002200,
            time: "2023-03-17 03:00",
            temp_c: 20.5,
            temp_f: 68.9,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 3.6,
            wind_kph: 5.8,
            wind_degree: 129,
            wind_dir: "SE",
            pressure_mb: 1012.0,
            pressure_in: 29.87,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 72,
            cloud: 8,
            feelslike_c: 20.5,
            feelslike_f: 68.9,
            windchill_c: 20.5,
            windchill_f: 68.9,
            heatindex_c: 20.5,
            heatindex_f: 68.9,
            dewpoint_c: 15.2,
            dewpoint_f: 59.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 5.4,
            gust_kph: 8.6,
            uv: 1.0,
          },
          {
            time_epoch: 1679005800,
            time: "2023-03-17 04:00",
            temp_c: 20.4,
            temp_f: 68.7,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 2.7,
            wind_kph: 4.3,
            wind_degree: 174,
            wind_dir: "S",
            pressure_mb: 1011.0,
            pressure_in: 29.87,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 71,
            cloud: 7,
            feelslike_c: 20.4,
            feelslike_f: 68.7,
            windchill_c: 20.4,
            windchill_f: 68.7,
            heatindex_c: 20.4,
            heatindex_f: 68.7,
            dewpoint_c: 15.0,
            dewpoint_f: 59.0,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 4.3,
            gust_kph: 6.8,
            uv: 1.0,
          },
          {
            time_epoch: 1679009400,
            time: "2023-03-17 05:00",
            temp_c: 20.2,
            temp_f: 68.4,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 2.5,
            wind_kph: 4.0,
            wind_degree: 173,
            wind_dir: "S",
            pressure_mb: 1012.0,
            pressure_in: 29.88,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 71,
            cloud: 8,
            feelslike_c: 20.2,
            feelslike_f: 68.4,
            windchill_c: 20.2,
            windchill_f: 68.4,
            heatindex_c: 20.2,
            heatindex_f: 68.4,
            dewpoint_c: 14.8,
            dewpoint_f: 58.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 4.0,
            gust_kph: 6.5,
            uv: 1.0,
          },
          {
            time_epoch: 1679013000,
            time: "2023-03-17 06:00",
            temp_c: 20.3,
            temp_f: 68.5,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 2.9,
            wind_kph: 4.7,
            wind_degree: 171,
            wind_dir: "S",
            pressure_mb: 1013.0,
            pressure_in: 29.9,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 70,
            cloud: 7,
            feelslike_c: 20.3,
            feelslike_f: 68.5,
            windchill_c: 20.3,
            windchill_f: 68.5,
            heatindex_c: 20.3,
            heatindex_f: 68.5,
            dewpoint_c: 14.6,
            dewpoint_f: 58.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 4.7,
            gust_kph: 7.6,
            uv: 1.0,
          },
          {
            time_epoch: 1679016600,
            time: "2023-03-17 07:00",
            temp_c: 21.3,
            temp_f: 70.3,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 2.5,
            wind_kph: 4.0,
            wind_degree: 176,
            wind_dir: "S",
            pressure_mb: 1013.0,
            pressure_in: 29.92,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 66,
            cloud: 7,
            feelslike_c: 21.3,
            feelslike_f: 70.3,
            windchill_c: 21.3,
            windchill_f: 70.3,
            heatindex_c: 24.4,
            heatindex_f: 75.9,
            dewpoint_c: 14.7,
            dewpoint_f: 58.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 3.4,
            gust_kph: 5.4,
            uv: 6.0,
          },
          {
            time_epoch: 1679020200,
            time: "2023-03-17 08:00",
            temp_c: 22.6,
            temp_f: 72.7,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 2.2,
            wind_kph: 3.6,
            wind_degree: 157,
            wind_dir: "SSE",
            pressure_mb: 1014.0,
            pressure_in: 29.94,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 59,
            cloud: 5,
            feelslike_c: 24.7,
            feelslike_f: 76.5,
            windchill_c: 22.6,
            windchill_f: 72.7,
            heatindex_c: 24.7,
            heatindex_f: 76.5,
            dewpoint_c: 14.1,
            dewpoint_f: 57.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 2.7,
            gust_kph: 4.3,
            uv: 6.0,
          },
          {
            time_epoch: 1679023800,
            time: "2023-03-17 09:00",
            temp_c: 24.6,
            temp_f: 76.3,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 3.1,
            wind_kph: 5.0,
            wind_degree: 119,
            wind_dir: "ESE",
            pressure_mb: 1014.0,
            pressure_in: 29.96,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 51,
            cloud: 10,
            feelslike_c: 25.6,
            feelslike_f: 78.1,
            windchill_c: 24.6,
            windchill_f: 76.3,
            heatindex_c: 25.6,
            heatindex_f: 78.1,
            dewpoint_c: 13.7,
            dewpoint_f: 56.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 3.6,
            gust_kph: 5.8,
            uv: 6.0,
          },
          {
            time_epoch: 1679027400,
            time: "2023-03-17 10:00",
            temp_c: 26.1,
            temp_f: 79.0,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 4.5,
            wind_kph: 7.2,
            wind_degree: 131,
            wind_dir: "SE",
            pressure_mb: 1014.0,
            pressure_in: 29.94,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 45,
            cloud: 8,
            feelslike_c: 26.4,
            feelslike_f: 79.5,
            windchill_c: 26.1,
            windchill_f: 79.0,
            heatindex_c: 26.4,
            heatindex_f: 79.5,
            dewpoint_c: 13.1,
            dewpoint_f: 55.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 5.1,
            gust_kph: 8.3,
            uv: 7.0,
          },
          {
            time_epoch: 1679031000,
            time: "2023-03-17 11:00",
            temp_c: 30.7,
            temp_f: 87.3,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 4.9,
            wind_kph: 7.9,
            wind_degree: 139,
            wind_dir: "SE",
            pressure_mb: 1013.0,
            pressure_in: 29.91,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 38,
            cloud: 15,
            feelslike_c: 30.8,
            feelslike_f: 87.4,
            windchill_c: 30.7,
            windchill_f: 87.3,
            heatindex_c: 30.8,
            heatindex_f: 87.4,
            dewpoint_c: 14.8,
            dewpoint_f: 58.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 5.6,
            gust_kph: 9.0,
            uv: 8.0,
          },
          {
            time_epoch: 1679034600,
            time: "2023-03-17 12:00",
            temp_c: 31.8,
            temp_f: 89.2,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 3.4,
            wind_kph: 5.4,
            wind_degree: 131,
            wind_dir: "SE",
            pressure_mb: 1012.0,
            pressure_in: 29.88,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 33,
            cloud: 14,
            feelslike_c: 31.4,
            feelslike_f: 88.5,
            windchill_c: 31.8,
            windchill_f: 89.2,
            heatindex_c: 31.4,
            heatindex_f: 88.5,
            dewpoint_c: 13.6,
            dewpoint_f: 56.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 3.8,
            gust_kph: 6.1,
            uv: 8.0,
          },
          {
            time_epoch: 1679038200,
            time: "2023-03-17 13:00",
            temp_c: 30.7,
            temp_f: 87.3,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 3.8,
            wind_kph: 6.1,
            wind_degree: 116,
            wind_dir: "ESE",
            pressure_mb: 1010.0,
            pressure_in: 29.83,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 30,
            cloud: 47,
            feelslike_c: 29.7,
            feelslike_f: 85.5,
            windchill_c: 30.7,
            windchill_f: 87.3,
            heatindex_c: 29.7,
            heatindex_f: 85.5,
            dewpoint_c: 11.1,
            dewpoint_f: 52.0,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 4.5,
            gust_kph: 7.2,
            uv: 8.0,
          },
          {
            time_epoch: 1679041800,
            time: "2023-03-17 14:00",
            temp_c: 30.8,
            temp_f: 87.4,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 2.2,
            wind_kph: 3.6,
            wind_degree: 157,
            wind_dir: "SSE",
            pressure_mb: 1009.0,
            pressure_in: 29.79,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 29,
            cloud: 40,
            feelslike_c: 29.6,
            feelslike_f: 85.3,
            windchill_c: 30.8,
            windchill_f: 87.4,
            heatindex_c: 29.6,
            heatindex_f: 85.3,
            dewpoint_c: 10.5,
            dewpoint_f: 50.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 2.5,
            gust_kph: 4.0,
            uv: 8.0,
          },
          {
            time_epoch: 1679045400,
            time: "2023-03-17 15:00",
            temp_c: 29.6,
            temp_f: 85.3,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 7.6,
            wind_kph: 12.2,
            wind_degree: 251,
            wind_dir: "WSW",
            pressure_mb: 1009.0,
            pressure_in: 29.78,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 34,
            cloud: 31,
            feelslike_c: 28.9,
            feelslike_f: 84.0,
            windchill_c: 29.6,
            windchill_f: 85.3,
            heatindex_c: 28.9,
            heatindex_f: 84.0,
            dewpoint_c: 12.1,
            dewpoint_f: 53.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 8.7,
            gust_kph: 14.0,
            uv: 7.0,
          },
          {
            time_epoch: 1679049000,
            time: "2023-03-17 16:00",
            temp_c: 26.3,
            temp_f: 79.3,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 10.7,
            wind_kph: 17.3,
            wind_degree: 261,
            wind_dir: "W",
            pressure_mb: 1009.0,
            pressure_in: 29.78,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 45,
            cloud: 16,
            feelslike_c: 26.6,
            feelslike_f: 79.9,
            windchill_c: 26.3,
            windchill_f: 79.3,
            heatindex_c: 26.6,
            heatindex_f: 79.9,
            dewpoint_c: 13.6,
            dewpoint_f: 56.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 13.4,
            gust_kph: 21.6,
            uv: 7.0,
          },
          {
            time_epoch: 1679052600,
            time: "2023-03-17 17:00",
            temp_c: 27.6,
            temp_f: 81.7,
            is_day: 1,
            condition: {
              text: "Patchy rain possible",
              icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
              code: 1063,
            },
            wind_mph: 8.9,
            wind_kph: 14.4,
            wind_degree: 271,
            wind_dir: "W",
            pressure_mb: 1009.0,
            pressure_in: 29.78,
            precip_mm: 0.1,
            precip_in: 0.0,
            humidity: 44,
            cloud: 78,
            feelslike_c: 27.8,
            feelslike_f: 82.0,
            windchill_c: 27.6,
            windchill_f: 81.7,
            heatindex_c: 27.8,
            heatindex_f: 82.0,
            dewpoint_c: 14.2,
            dewpoint_f: 57.6,
            will_it_rain: 1,
            chance_of_rain: 72,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 10.3,
            gust_kph: 16.6,
            uv: 6.0,
          },
          {
            time_epoch: 1679056200,
            time: "2023-03-17 18:00",
            temp_c: 26.6,
            temp_f: 79.9,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 8.7,
            wind_kph: 14.0,
            wind_degree: 286,
            wind_dir: "WNW",
            pressure_mb: 1009.0,
            pressure_in: 29.8,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 45,
            cloud: 16,
            feelslike_c: 26.9,
            feelslike_f: 80.4,
            windchill_c: 26.6,
            windchill_f: 79.9,
            heatindex_c: 26.9,
            heatindex_f: 80.4,
            dewpoint_c: 13.8,
            dewpoint_f: 56.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 10.1,
            gust_kph: 16.2,
            uv: 7.0,
          },
          {
            time_epoch: 1679059800,
            time: "2023-03-17 19:00",
            temp_c: 25.4,
            temp_f: 77.7,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 11.0,
            wind_kph: 17.6,
            wind_degree: 301,
            wind_dir: "WNW",
            pressure_mb: 1010.0,
            pressure_in: 29.83,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 55,
            cloud: 14,
            feelslike_c: 26.3,
            feelslike_f: 79.3,
            windchill_c: 25.4,
            windchill_f: 77.7,
            heatindex_c: 26.3,
            heatindex_f: 79.3,
            dewpoint_c: 15.6,
            dewpoint_f: 60.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 12.5,
            gust_kph: 20.2,
            uv: 1.0,
          },
          {
            time_epoch: 1679063400,
            time: "2023-03-17 20:00",
            temp_c: 23.5,
            temp_f: 74.3,
            is_day: 0,
            condition: {
              text: "Patchy rain possible",
              icon: "//cdn.weatherapi.com/weather/64x64/night/176.png",
              code: 1063,
            },
            wind_mph: 7.6,
            wind_kph: 12.2,
            wind_degree: 286,
            wind_dir: "WNW",
            pressure_mb: 1011.0,
            pressure_in: 29.86,
            precip_mm: 0.1,
            precip_in: 0.0,
            humidity: 62,
            cloud: 73,
            feelslike_c: 25.2,
            feelslike_f: 77.4,
            windchill_c: 23.5,
            windchill_f: 74.3,
            heatindex_c: 25.2,
            heatindex_f: 77.4,
            dewpoint_c: 15.8,
            dewpoint_f: 60.4,
            will_it_rain: 1,
            chance_of_rain: 85,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 9.6,
            gust_kph: 15.5,
            uv: 1.0,
          },
          {
            time_epoch: 1679067000,
            time: "2023-03-17 21:00",
            temp_c: 23.3,
            temp_f: 73.9,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 6.5,
            wind_kph: 10.4,
            wind_degree: 265,
            wind_dir: "W",
            pressure_mb: 1012.0,
            pressure_in: 29.87,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 63,
            cloud: 14,
            feelslike_c: 25.1,
            feelslike_f: 77.2,
            windchill_c: 23.3,
            windchill_f: 73.9,
            heatindex_c: 25.1,
            heatindex_f: 77.2,
            dewpoint_c: 15.9,
            dewpoint_f: 60.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 8.5,
            gust_kph: 13.7,
            uv: 1.0,
          },
          {
            time_epoch: 1679070600,
            time: "2023-03-17 22:00",
            temp_c: 23.0,
            temp_f: 73.4,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 5.8,
            wind_kph: 9.4,
            wind_degree: 269,
            wind_dir: "W",
            pressure_mb: 1012.0,
            pressure_in: 29.88,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 66,
            cloud: 16,
            feelslike_c: 25.0,
            feelslike_f: 77.0,
            windchill_c: 23.0,
            windchill_f: 73.4,
            heatindex_c: 25.0,
            heatindex_f: 77.0,
            dewpoint_c: 16.3,
            dewpoint_f: 61.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 7.8,
            gust_kph: 12.6,
            uv: 1.0,
          },
          {
            time_epoch: 1679074200,
            time: "2023-03-17 23:00",
            temp_c: 22.7,
            temp_f: 72.9,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 5.4,
            wind_kph: 8.6,
            wind_degree: 274,
            wind_dir: "W",
            pressure_mb: 1012.0,
            pressure_in: 29.87,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 69,
            cloud: 17,
            feelslike_c: 24.8,
            feelslike_f: 76.6,
            windchill_c: 22.7,
            windchill_f: 72.9,
            heatindex_c: 24.8,
            heatindex_f: 76.6,
            dewpoint_c: 16.7,
            dewpoint_f: 62.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 7.4,
            gust_kph: 11.9,
            uv: 1.0,
          },
        ],
      },
      {
        date: "2023-03-18",
        date_epoch: 1679097600,
        day: {
          maxtemp_c: 31.5,
          maxtemp_f: 88.7,
          mintemp_c: 20.3,
          mintemp_f: 68.5,
          avgtemp_c: 25.4,
          avgtemp_f: 77.8,
          maxwind_mph: 9.6,
          maxwind_kph: 15.5,
          totalprecip_mm: 0.4,
          totalprecip_in: 0.02,
          totalsnow_cm: 0.0,
          avgvis_km: 10.0,
          avgvis_miles: 6.0,
          avghumidity: 53.0,
          daily_will_it_rain: 1,
          daily_chance_of_rain: 88,
          daily_will_it_snow: 0,
          daily_chance_of_snow: 0,
          condition: {
            text: "Patchy rain possible",
            icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
            code: 1063,
          },
          uv: 6.0,
        },
        astro: {
          sunrise: "06:41 AM",
          sunset: "06:45 PM",
          moonrise: "04:03 AM",
          moonset: "03:23 PM",
          moon_phase: "Waning Crescent",
          moon_illumination: "19",
          is_moon_up: 1,
          is_sun_up: 0,
        },
        hour: [
          {
            time_epoch: 1679077800,
            time: "2023-03-18 00:00",
            temp_c: 22.0,
            temp_f: 71.6,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 5.4,
            wind_kph: 8.6,
            wind_degree: 271,
            wind_dir: "W",
            pressure_mb: 1011.0,
            pressure_in: 29.86,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 71,
            cloud: 16,
            feelslike_c: 24.6,
            feelslike_f: 76.3,
            windchill_c: 22.0,
            windchill_f: 71.6,
            heatindex_c: 24.6,
            heatindex_f: 76.3,
            dewpoint_c: 16.6,
            dewpoint_f: 61.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 8.1,
            gust_kph: 13.0,
            uv: 1.0,
          },
          {
            time_epoch: 1679081400,
            time: "2023-03-18 01:00",
            temp_c: 21.9,
            temp_f: 71.4,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 5.4,
            wind_kph: 8.6,
            wind_degree: 279,
            wind_dir: "W",
            pressure_mb: 1011.0,
            pressure_in: 29.84,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 72,
            cloud: 14,
            feelslike_c: 21.9,
            feelslike_f: 71.4,
            windchill_c: 21.9,
            windchill_f: 71.4,
            heatindex_c: 24.5,
            heatindex_f: 76.1,
            dewpoint_c: 16.6,
            dewpoint_f: 61.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 7.8,
            gust_kph: 12.6,
            uv: 1.0,
          },
          {
            time_epoch: 1679085000,
            time: "2023-03-18 02:00",
            temp_c: 21.7,
            temp_f: 71.1,
            is_day: 0,
            condition: {
              text: "Patchy rain possible",
              icon: "//cdn.weatherapi.com/weather/64x64/night/176.png",
              code: 1063,
            },
            wind_mph: 4.9,
            wind_kph: 7.9,
            wind_degree: 295,
            wind_dir: "WNW",
            pressure_mb: 1010.0,
            pressure_in: 29.83,
            precip_mm: 0.1,
            precip_in: 0.0,
            humidity: 72,
            cloud: 84,
            feelslike_c: 21.7,
            feelslike_f: 71.1,
            windchill_c: 21.7,
            windchill_f: 71.1,
            heatindex_c: 24.5,
            heatindex_f: 76.1,
            dewpoint_c: 16.5,
            dewpoint_f: 61.7,
            will_it_rain: 1,
            chance_of_rain: 79,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 7.4,
            gust_kph: 11.9,
            uv: 1.0,
          },
          {
            time_epoch: 1679088600,
            time: "2023-03-18 03:00",
            temp_c: 21.2,
            temp_f: 70.2,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 3.8,
            wind_kph: 6.1,
            wind_degree: 328,
            wind_dir: "NNW",
            pressure_mb: 1010.0,
            pressure_in: 29.82,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 74,
            cloud: 12,
            feelslike_c: 21.2,
            feelslike_f: 70.2,
            windchill_c: 21.2,
            windchill_f: 70.2,
            heatindex_c: 24.4,
            heatindex_f: 75.9,
            dewpoint_c: 16.4,
            dewpoint_f: 61.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 6.0,
            gust_kph: 9.7,
            uv: 1.0,
          },
          {
            time_epoch: 1679092200,
            time: "2023-03-18 04:00",
            temp_c: 21.0,
            temp_f: 69.8,
            is_day: 0,
            condition: {
              text: "Patchy rain possible",
              icon: "//cdn.weatherapi.com/weather/64x64/night/176.png",
              code: 1063,
            },
            wind_mph: 3.4,
            wind_kph: 5.4,
            wind_degree: 350,
            wind_dir: "N",
            pressure_mb: 1010.0,
            pressure_in: 29.83,
            precip_mm: 0.1,
            precip_in: 0.0,
            humidity: 74,
            cloud: 79,
            feelslike_c: 21.0,
            feelslike_f: 69.8,
            windchill_c: 21.0,
            windchill_f: 69.8,
            heatindex_c: 21.0,
            heatindex_f: 69.8,
            dewpoint_c: 16.2,
            dewpoint_f: 61.2,
            will_it_rain: 0,
            chance_of_rain: 64,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 5.4,
            gust_kph: 8.6,
            uv: 1.0,
          },
          {
            time_epoch: 1679095800,
            time: "2023-03-18 05:00",
            temp_c: 20.9,
            temp_f: 69.6,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 3.4,
            wind_kph: 5.4,
            wind_degree: 3,
            wind_dir: "N",
            pressure_mb: 1011.0,
            pressure_in: 29.84,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 72,
            cloud: 9,
            feelslike_c: 20.9,
            feelslike_f: 69.6,
            windchill_c: 20.9,
            windchill_f: 69.6,
            heatindex_c: 20.9,
            heatindex_f: 69.6,
            dewpoint_c: 15.7,
            dewpoint_f: 60.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 5.4,
            gust_kph: 8.6,
            uv: 1.0,
          },
          {
            time_epoch: 1679099400,
            time: "2023-03-18 06:00",
            temp_c: 20.7,
            temp_f: 69.3,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 2.9,
            wind_kph: 4.7,
            wind_degree: 22,
            wind_dir: "NNE",
            pressure_mb: 1011.0,
            pressure_in: 29.87,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 71,
            cloud: 10,
            feelslike_c: 20.7,
            feelslike_f: 69.3,
            windchill_c: 20.7,
            windchill_f: 69.3,
            heatindex_c: 20.7,
            heatindex_f: 69.3,
            dewpoint_c: 15.2,
            dewpoint_f: 59.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 4.7,
            gust_kph: 7.6,
            uv: 1.0,
          },
          {
            time_epoch: 1679103000,
            time: "2023-03-18 07:00",
            temp_c: 21.7,
            temp_f: 71.1,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 3.1,
            wind_kph: 5.0,
            wind_degree: 44,
            wind_dir: "NE",
            pressure_mb: 1012.0,
            pressure_in: 29.89,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 65,
            cloud: 12,
            feelslike_c: 21.7,
            feelslike_f: 71.1,
            windchill_c: 21.7,
            windchill_f: 71.1,
            heatindex_c: 24.5,
            heatindex_f: 76.1,
            dewpoint_c: 14.8,
            dewpoint_f: 58.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 4.3,
            gust_kph: 6.8,
            uv: 6.0,
          },
          {
            time_epoch: 1679106600,
            time: "2023-03-18 08:00",
            temp_c: 23.6,
            temp_f: 74.5,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 6.3,
            wind_kph: 10.1,
            wind_degree: 51,
            wind_dir: "NE",
            pressure_mb: 1013.0,
            pressure_in: 29.91,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 55,
            cloud: 11,
            feelslike_c: 25.1,
            feelslike_f: 77.2,
            windchill_c: 23.6,
            windchill_f: 74.5,
            heatindex_c: 25.1,
            heatindex_f: 77.2,
            dewpoint_c: 14.2,
            dewpoint_f: 57.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 7.2,
            gust_kph: 11.5,
            uv: 6.0,
          },
          {
            time_epoch: 1679110200,
            time: "2023-03-18 09:00",
            temp_c: 25.4,
            temp_f: 77.7,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 8.7,
            wind_kph: 14.0,
            wind_degree: 45,
            wind_dir: "NE",
            pressure_mb: 1013.0,
            pressure_in: 29.91,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 49,
            cloud: 11,
            feelslike_c: 26.1,
            feelslike_f: 79.0,
            windchill_c: 25.4,
            windchill_f: 77.7,
            heatindex_c: 26.1,
            heatindex_f: 79.0,
            dewpoint_c: 13.8,
            dewpoint_f: 56.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 10.1,
            gust_kph: 16.2,
            uv: 7.0,
          },
          {
            time_epoch: 1679113800,
            time: "2023-03-18 10:00",
            temp_c: 27.1,
            temp_f: 80.8,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 9.2,
            wind_kph: 14.8,
            wind_degree: 44,
            wind_dir: "NE",
            pressure_mb: 1013.0,
            pressure_in: 29.9,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 43,
            cloud: 24,
            feelslike_c: 27.2,
            feelslike_f: 81.0,
            windchill_c: 27.1,
            windchill_f: 80.8,
            heatindex_c: 27.2,
            heatindex_f: 81.0,
            dewpoint_c: 13.4,
            dewpoint_f: 56.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 10.5,
            gust_kph: 16.9,
            uv: 7.0,
          },
          {
            time_epoch: 1679117400,
            time: "2023-03-18 11:00",
            temp_c: 30.7,
            temp_f: 87.3,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 8.5,
            wind_kph: 13.7,
            wind_degree: 45,
            wind_dir: "NE",
            pressure_mb: 1012.0,
            pressure_in: 29.87,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 38,
            cloud: 16,
            feelslike_c: 30.8,
            feelslike_f: 87.4,
            windchill_c: 30.7,
            windchill_f: 87.3,
            heatindex_c: 30.8,
            heatindex_f: 87.4,
            dewpoint_c: 14.9,
            dewpoint_f: 58.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 9.8,
            gust_kph: 15.8,
            uv: 8.0,
          },
          {
            time_epoch: 1679121000,
            time: "2023-03-18 12:00",
            temp_c: 30.4,
            temp_f: 86.7,
            is_day: 1,
            condition: {
              text: "Cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/119.png",
              code: 1006,
            },
            wind_mph: 6.0,
            wind_kph: 9.7,
            wind_degree: 36,
            wind_dir: "NE",
            pressure_mb: 1010.0,
            pressure_in: 29.83,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 33,
            cloud: 67,
            feelslike_c: 29.8,
            feelslike_f: 85.6,
            windchill_c: 30.4,
            windchill_f: 86.7,
            heatindex_c: 29.8,
            heatindex_f: 85.6,
            dewpoint_c: 12.5,
            dewpoint_f: 54.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 6.9,
            gust_kph: 11.2,
            uv: 7.0,
          },
          {
            time_epoch: 1679124600,
            time: "2023-03-18 13:00",
            temp_c: 31.4,
            temp_f: 88.5,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 2.7,
            wind_kph: 4.3,
            wind_degree: 20,
            wind_dir: "NNE",
            pressure_mb: 1009.0,
            pressure_in: 29.79,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 29,
            cloud: 46,
            feelslike_c: 30.3,
            feelslike_f: 86.5,
            windchill_c: 31.4,
            windchill_f: 88.5,
            heatindex_c: 30.3,
            heatindex_f: 86.5,
            dewpoint_c: 11.2,
            dewpoint_f: 52.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 3.1,
            gust_kph: 5.0,
            uv: 8.0,
          },
          {
            time_epoch: 1679128200,
            time: "2023-03-18 14:00",
            temp_c: 31.8,
            temp_f: 89.2,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 0.4,
            wind_kph: 0.7,
            wind_degree: 342,
            wind_dir: "NNW",
            pressure_mb: 1008.0,
            pressure_in: 29.75,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 27,
            cloud: 29,
            feelslike_c: 30.5,
            feelslike_f: 86.9,
            windchill_c: 31.8,
            windchill_f: 89.2,
            heatindex_c: 30.5,
            heatindex_f: 86.9,
            dewpoint_c: 10.5,
            dewpoint_f: 50.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 0.4,
            gust_kph: 0.7,
            uv: 8.0,
          },
          {
            time_epoch: 1679131800,
            time: "2023-03-18 15:00",
            temp_c: 31.2,
            temp_f: 88.2,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 1.8,
            wind_kph: 2.9,
            wind_degree: 0,
            wind_dir: "N",
            pressure_mb: 1007.0,
            pressure_in: 29.72,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 28,
            cloud: 25,
            feelslike_c: 29.9,
            feelslike_f: 85.8,
            windchill_c: 31.2,
            windchill_f: 88.2,
            heatindex_c: 29.9,
            heatindex_f: 85.8,
            dewpoint_c: 10.5,
            dewpoint_f: 50.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 2.0,
            gust_kph: 3.2,
            uv: 8.0,
          },
          {
            time_epoch: 1679135400,
            time: "2023-03-18 16:00",
            temp_c: 30.2,
            temp_f: 86.4,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 6.3,
            wind_kph: 10.1,
            wind_degree: 332,
            wind_dir: "NNW",
            pressure_mb: 1006.0,
            pressure_in: 29.71,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 30,
            cloud: 25,
            feelslike_c: 29.2,
            feelslike_f: 84.6,
            windchill_c: 30.2,
            windchill_f: 86.4,
            heatindex_c: 29.2,
            heatindex_f: 84.6,
            dewpoint_c: 10.9,
            dewpoint_f: 51.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 7.2,
            gust_kph: 11.5,
            uv: 8.0,
          },
          {
            time_epoch: 1679139000,
            time: "2023-03-18 17:00",
            temp_c: 29.1,
            temp_f: 84.4,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 8.9,
            wind_kph: 14.4,
            wind_degree: 309,
            wind_dir: "NW",
            pressure_mb: 1007.0,
            pressure_in: 29.72,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 33,
            cloud: 31,
            feelslike_c: 28.3,
            feelslike_f: 82.9,
            windchill_c: 29.1,
            windchill_f: 84.4,
            heatindex_c: 28.3,
            heatindex_f: 82.9,
            dewpoint_c: 11.1,
            dewpoint_f: 52.0,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 10.3,
            gust_kph: 16.6,
            uv: 7.0,
          },
          {
            time_epoch: 1679142600,
            time: "2023-03-18 18:00",
            temp_c: 28.0,
            temp_f: 82.4,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 8.3,
            wind_kph: 13.3,
            wind_degree: 278,
            wind_dir: "W",
            pressure_mb: 1007.0,
            pressure_in: 29.74,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 40,
            cloud: 23,
            feelslike_c: 27.8,
            feelslike_f: 82.0,
            windchill_c: 28.0,
            windchill_f: 82.4,
            heatindex_c: 27.8,
            heatindex_f: 82.0,
            dewpoint_c: 13.0,
            dewpoint_f: 55.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 9.6,
            gust_kph: 15.5,
            uv: 7.0,
          },
          {
            time_epoch: 1679146200,
            time: "2023-03-18 19:00",
            temp_c: 27.0,
            temp_f: 80.6,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 8.7,
            wind_kph: 14.0,
            wind_degree: 263,
            wind_dir: "W",
            pressure_mb: 1008.0,
            pressure_in: 29.77,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 48,
            cloud: 14,
            feelslike_c: 27.4,
            feelslike_f: 81.3,
            windchill_c: 27.0,
            windchill_f: 80.6,
            heatindex_c: 27.4,
            heatindex_f: 81.3,
            dewpoint_c: 14.9,
            dewpoint_f: 58.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 10.1,
            gust_kph: 16.2,
            uv: 1.0,
          },
          {
            time_epoch: 1679149800,
            time: "2023-03-18 20:00",
            temp_c: 24.9,
            temp_f: 76.8,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 8.7,
            wind_kph: 14.0,
            wind_degree: 266,
            wind_dir: "W",
            pressure_mb: 1009.0,
            pressure_in: 29.8,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 53,
            cloud: 12,
            feelslike_c: 25.9,
            feelslike_f: 78.6,
            windchill_c: 24.9,
            windchill_f: 76.8,
            heatindex_c: 25.9,
            heatindex_f: 78.6,
            dewpoint_c: 14.7,
            dewpoint_f: 58.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 11.4,
            gust_kph: 18.4,
            uv: 1.0,
          },
          {
            time_epoch: 1679153400,
            time: "2023-03-18 21:00",
            temp_c: 24.1,
            temp_f: 75.4,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 7.6,
            wind_kph: 12.2,
            wind_degree: 270,
            wind_dir: "W",
            pressure_mb: 1010.0,
            pressure_in: 29.83,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 57,
            cloud: 9,
            feelslike_c: 25.4,
            feelslike_f: 77.7,
            windchill_c: 24.1,
            windchill_f: 75.4,
            heatindex_c: 25.4,
            heatindex_f: 77.7,
            dewpoint_c: 14.9,
            dewpoint_f: 58.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 9.8,
            gust_kph: 15.8,
            uv: 1.0,
          },
          {
            time_epoch: 1679157000,
            time: "2023-03-18 22:00",
            temp_c: 23.2,
            temp_f: 73.8,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 6.7,
            wind_kph: 10.8,
            wind_degree: 270,
            wind_dir: "W",
            pressure_mb: 1011.0,
            pressure_in: 29.85,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 61,
            cloud: 6,
            feelslike_c: 25.0,
            feelslike_f: 77.0,
            windchill_c: 23.2,
            windchill_f: 73.8,
            heatindex_c: 25.0,
            heatindex_f: 77.0,
            dewpoint_c: 15.1,
            dewpoint_f: 59.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 8.9,
            gust_kph: 14.4,
            uv: 1.0,
          },
          {
            time_epoch: 1679160600,
            time: "2023-03-18 23:00",
            temp_c: 22.6,
            temp_f: 72.7,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 6.7,
            wind_kph: 10.8,
            wind_degree: 268,
            wind_dir: "W",
            pressure_mb: 1011.0,
            pressure_in: 29.84,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 63,
            cloud: 5,
            feelslike_c: 24.8,
            feelslike_f: 76.6,
            windchill_c: 22.6,
            windchill_f: 72.7,
            heatindex_c: 24.8,
            heatindex_f: 76.6,
            dewpoint_c: 15.3,
            dewpoint_f: 59.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 8.9,
            gust_kph: 14.4,
            uv: 1.0,
          },
        ],
      },
      {
        date: "2023-03-19",
        date_epoch: 1679184000,
        day: {
          maxtemp_c: 33.4,
          maxtemp_f: 92.1,
          mintemp_c: 19.0,
          mintemp_f: 66.2,
          avgtemp_c: 25.0,
          avgtemp_f: 77.1,
          maxwind_mph: 17.0,
          maxwind_kph: 27.4,
          totalprecip_mm: 0.0,
          totalprecip_in: 0.0,
          totalsnow_cm: 0.0,
          avgvis_km: 10.0,
          avgvis_miles: 6.0,
          avghumidity: 50.0,
          daily_will_it_rain: 0,
          daily_chance_of_rain: 0,
          daily_will_it_snow: 0,
          daily_chance_of_snow: 0,
          condition: {
            text: "Sunny",
            icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
            code: 1000,
          },
          uv: 7.0,
        },
        astro: {
          sunrise: "06:40 AM",
          sunset: "06:45 PM",
          moonrise: "04:54 AM",
          moonset: "04:29 PM",
          moon_phase: "Waning Crescent",
          moon_illumination: "10",
          is_moon_up: 1,
          is_sun_up: 0,
        },
        hour: [
          {
            time_epoch: 1679164200,
            time: "2023-03-19 00:00",
            temp_c: 21.6,
            temp_f: 70.9,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 6.0,
            wind_kph: 9.7,
            wind_degree: 274,
            wind_dir: "W",
            pressure_mb: 1010.0,
            pressure_in: 29.83,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 66,
            cloud: 4,
            feelslike_c: 21.6,
            feelslike_f: 70.9,
            windchill_c: 21.6,
            windchill_f: 70.9,
            heatindex_c: 24.5,
            heatindex_f: 76.1,
            dewpoint_c: 15.1,
            dewpoint_f: 59.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 8.7,
            gust_kph: 14.0,
            uv: 1.0,
          },
          {
            time_epoch: 1679167800,
            time: "2023-03-19 01:00",
            temp_c: 20.8,
            temp_f: 69.4,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 5.1,
            wind_kph: 8.3,
            wind_degree: 278,
            wind_dir: "W",
            pressure_mb: 1010.0,
            pressure_in: 29.83,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 70,
            cloud: 2,
            feelslike_c: 20.8,
            feelslike_f: 69.4,
            windchill_c: 20.8,
            windchill_f: 69.4,
            heatindex_c: 20.8,
            heatindex_f: 69.4,
            dewpoint_c: 15.1,
            dewpoint_f: 59.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 7.8,
            gust_kph: 12.6,
            uv: 1.0,
          },
          {
            time_epoch: 1679171400,
            time: "2023-03-19 02:00",
            temp_c: 20.3,
            temp_f: 68.5,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 5.1,
            wind_kph: 8.3,
            wind_degree: 291,
            wind_dir: "WNW",
            pressure_mb: 1010.0,
            pressure_in: 29.82,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 72,
            cloud: 0,
            feelslike_c: 20.3,
            feelslike_f: 68.5,
            windchill_c: 20.3,
            windchill_f: 68.5,
            heatindex_c: 20.3,
            heatindex_f: 68.5,
            dewpoint_c: 15.1,
            dewpoint_f: 59.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 7.8,
            gust_kph: 12.6,
            uv: 1.0,
          },
          {
            time_epoch: 1679175000,
            time: "2023-03-19 03:00",
            temp_c: 19.7,
            temp_f: 67.5,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 4.9,
            wind_kph: 7.9,
            wind_degree: 280,
            wind_dir: "W",
            pressure_mb: 1010.0,
            pressure_in: 29.81,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 73,
            cloud: 0,
            feelslike_c: 19.7,
            feelslike_f: 67.5,
            windchill_c: 19.7,
            windchill_f: 67.5,
            heatindex_c: 19.7,
            heatindex_f: 67.5,
            dewpoint_c: 14.8,
            dewpoint_f: 58.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 7.8,
            gust_kph: 12.6,
            uv: 1.0,
          },
          {
            time_epoch: 1679178600,
            time: "2023-03-19 04:00",
            temp_c: 19.3,
            temp_f: 66.7,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 5.1,
            wind_kph: 8.3,
            wind_degree: 274,
            wind_dir: "W",
            pressure_mb: 1010.0,
            pressure_in: 29.82,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 75,
            cloud: 0,
            feelslike_c: 19.3,
            feelslike_f: 66.7,
            windchill_c: 19.3,
            windchill_f: 66.7,
            heatindex_c: 19.3,
            heatindex_f: 66.7,
            dewpoint_c: 14.8,
            dewpoint_f: 58.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 8.3,
            gust_kph: 13.3,
            uv: 1.0,
          },
          {
            time_epoch: 1679182200,
            time: "2023-03-19 05:00",
            temp_c: 18.9,
            temp_f: 66.0,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 4.9,
            wind_kph: 7.9,
            wind_degree: 275,
            wind_dir: "W",
            pressure_mb: 1010.0,
            pressure_in: 29.83,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 77,
            cloud: 0,
            feelslike_c: 18.9,
            feelslike_f: 66.0,
            windchill_c: 18.9,
            windchill_f: 66.0,
            heatindex_c: 18.9,
            heatindex_f: 66.0,
            dewpoint_c: 14.8,
            dewpoint_f: 58.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 8.1,
            gust_kph: 13.0,
            uv: 1.0,
          },
          {
            time_epoch: 1679185800,
            time: "2023-03-19 06:00",
            temp_c: 18.6,
            temp_f: 65.5,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 4.5,
            wind_kph: 7.2,
            wind_degree: 274,
            wind_dir: "W",
            pressure_mb: 1011.0,
            pressure_in: 29.85,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 79,
            cloud: 0,
            feelslike_c: 18.6,
            feelslike_f: 65.5,
            windchill_c: 18.6,
            windchill_f: 65.5,
            heatindex_c: 18.6,
            heatindex_f: 65.5,
            dewpoint_c: 14.8,
            dewpoint_f: 58.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 7.6,
            gust_kph: 12.2,
            uv: 1.0,
          },
          {
            time_epoch: 1679189400,
            time: "2023-03-19 07:00",
            temp_c: 19.8,
            temp_f: 67.6,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 4.3,
            wind_kph: 6.8,
            wind_degree: 282,
            wind_dir: "WNW",
            pressure_mb: 1011.0,
            pressure_in: 29.87,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 75,
            cloud: 0,
            feelslike_c: 19.8,
            feelslike_f: 67.6,
            windchill_c: 19.8,
            windchill_f: 67.6,
            heatindex_c: 19.8,
            heatindex_f: 67.6,
            dewpoint_c: 15.2,
            dewpoint_f: 59.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 5.8,
            gust_kph: 9.4,
            uv: 5.0,
          },
          {
            time_epoch: 1679193000,
            time: "2023-03-19 08:00",
            temp_c: 21.9,
            temp_f: 71.4,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 5.1,
            wind_kph: 8.3,
            wind_degree: 302,
            wind_dir: "WNW",
            pressure_mb: 1012.0,
            pressure_in: 29.89,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 63,
            cloud: 0,
            feelslike_c: 21.9,
            feelslike_f: 71.4,
            windchill_c: 21.9,
            windchill_f: 71.4,
            heatindex_c: 24.6,
            heatindex_f: 76.3,
            dewpoint_c: 14.5,
            dewpoint_f: 58.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 5.8,
            gust_kph: 9.4,
            uv: 6.0,
          },
          {
            time_epoch: 1679196600,
            time: "2023-03-19 09:00",
            temp_c: 23.8,
            temp_f: 74.8,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 4.7,
            wind_kph: 7.6,
            wind_degree: 319,
            wind_dir: "NW",
            pressure_mb: 1012.0,
            pressure_in: 29.89,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 49,
            cloud: 0,
            feelslike_c: 25.1,
            feelslike_f: 77.2,
            windchill_c: 23.8,
            windchill_f: 74.8,
            heatindex_c: 25.1,
            heatindex_f: 77.2,
            dewpoint_c: 12.6,
            dewpoint_f: 54.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 5.4,
            gust_kph: 8.6,
            uv: 6.0,
          },
          {
            time_epoch: 1679200200,
            time: "2023-03-19 10:00",
            temp_c: 25.7,
            temp_f: 78.3,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 4.0,
            wind_kph: 6.5,
            wind_degree: 317,
            wind_dir: "NW",
            pressure_mb: 1012.0,
            pressure_in: 29.88,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 38,
            cloud: 3,
            feelslike_c: 25.7,
            feelslike_f: 78.3,
            windchill_c: 25.7,
            windchill_f: 78.3,
            heatindex_c: 25.7,
            heatindex_f: 78.3,
            dewpoint_c: 10.5,
            dewpoint_f: 50.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 4.7,
            gust_kph: 7.6,
            uv: 7.0,
          },
          {
            time_epoch: 1679203800,
            time: "2023-03-19 11:00",
            temp_c: 30.3,
            temp_f: 86.5,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 3.1,
            wind_kph: 5.0,
            wind_degree: 314,
            wind_dir: "NW",
            pressure_mb: 1011.0,
            pressure_in: 29.85,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 30,
            cloud: 4,
            feelslike_c: 29.2,
            feelslike_f: 84.6,
            windchill_c: 30.3,
            windchill_f: 86.5,
            heatindex_c: 29.2,
            heatindex_f: 84.6,
            dewpoint_c: 10.7,
            dewpoint_f: 51.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 3.6,
            gust_kph: 5.8,
            uv: 8.0,
          },
          {
            time_epoch: 1679207400,
            time: "2023-03-19 12:00",
            temp_c: 31.5,
            temp_f: 88.7,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 3.4,
            wind_kph: 5.4,
            wind_degree: 286,
            wind_dir: "WNW",
            pressure_mb: 1009.0,
            pressure_in: 29.81,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 24,
            cloud: 11,
            feelslike_c: 29.8,
            feelslike_f: 85.6,
            windchill_c: 31.5,
            windchill_f: 88.7,
            heatindex_c: 29.8,
            heatindex_f: 85.6,
            dewpoint_c: 8.7,
            dewpoint_f: 47.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 3.8,
            gust_kph: 6.1,
            uv: 8.0,
          },
          {
            time_epoch: 1679211000,
            time: "2023-03-19 13:00",
            temp_c: 32.4,
            temp_f: 90.3,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 4.5,
            wind_kph: 7.2,
            wind_degree: 274,
            wind_dir: "W",
            pressure_mb: 1008.0,
            pressure_in: 29.76,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 21,
            cloud: 11,
            feelslike_c: 30.4,
            feelslike_f: 86.7,
            windchill_c: 32.4,
            windchill_f: 90.3,
            heatindex_c: 30.4,
            heatindex_f: 86.7,
            dewpoint_c: 7.6,
            dewpoint_f: 45.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 5.1,
            gust_kph: 8.3,
            uv: 8.0,
          },
          {
            time_epoch: 1679214600,
            time: "2023-03-19 14:00",
            temp_c: 33.3,
            temp_f: 91.9,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 7.2,
            wind_kph: 11.5,
            wind_degree: 267,
            wind_dir: "W",
            pressure_mb: 1007.0,
            pressure_in: 29.72,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 20,
            cloud: 8,
            feelslike_c: 31.2,
            feelslike_f: 88.2,
            windchill_c: 33.3,
            windchill_f: 91.9,
            heatindex_c: 31.2,
            heatindex_f: 88.2,
            dewpoint_c: 7.2,
            dewpoint_f: 45.0,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 8.3,
            gust_kph: 13.3,
            uv: 8.0,
          },
          {
            time_epoch: 1679218200,
            time: "2023-03-19 15:00",
            temp_c: 32.6,
            temp_f: 90.7,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 9.8,
            wind_kph: 15.8,
            wind_degree: 266,
            wind_dir: "W",
            pressure_mb: 1006.0,
            pressure_in: 29.7,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 20,
            cloud: 8,
            feelslike_c: 30.4,
            feelslike_f: 86.7,
            windchill_c: 32.6,
            windchill_f: 90.7,
            heatindex_c: 30.4,
            heatindex_f: 86.7,
            dewpoint_c: 6.6,
            dewpoint_f: 43.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 11.4,
            gust_kph: 18.4,
            uv: 8.0,
          },
          {
            time_epoch: 1679221800,
            time: "2023-03-19 16:00",
            temp_c: 31.2,
            temp_f: 88.2,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 12.1,
            wind_kph: 19.4,
            wind_degree: 265,
            wind_dir: "W",
            pressure_mb: 1006.0,
            pressure_in: 29.7,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 22,
            cloud: 11,
            feelslike_c: 29.2,
            feelslike_f: 84.6,
            windchill_c: 31.2,
            windchill_f: 88.2,
            heatindex_c: 29.2,
            heatindex_f: 84.6,
            dewpoint_c: 7.1,
            dewpoint_f: 44.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 13.9,
            gust_kph: 22.3,
            uv: 8.0,
          },
          {
            time_epoch: 1679225400,
            time: "2023-03-19 17:00",
            temp_c: 31.4,
            temp_f: 88.5,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 17.2,
            wind_kph: 27.7,
            wind_degree: 272,
            wind_dir: "W",
            pressure_mb: 1006.0,
            pressure_in: 29.7,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 29,
            cloud: 12,
            feelslike_c: 30.4,
            feelslike_f: 86.7,
            windchill_c: 31.4,
            windchill_f: 88.5,
            heatindex_c: 30.4,
            heatindex_f: 86.7,
            dewpoint_c: 11.4,
            dewpoint_f: 52.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 19.9,
            gust_kph: 32.0,
            uv: 8.0,
          },
          {
            time_epoch: 1679229000,
            time: "2023-03-19 18:00",
            temp_c: 28.0,
            temp_f: 82.4,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 17.2,
            wind_kph: 27.7,
            wind_degree: 274,
            wind_dir: "W",
            pressure_mb: 1007.0,
            pressure_in: 29.74,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 37,
            cloud: 7,
            feelslike_c: 27.6,
            feelslike_f: 81.7,
            windchill_c: 28.0,
            windchill_f: 82.4,
            heatindex_c: 27.6,
            heatindex_f: 81.7,
            dewpoint_c: 12.0,
            dewpoint_f: 53.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 19.9,
            gust_kph: 32.0,
            uv: 7.0,
          },
          {
            time_epoch: 1679232600,
            time: "2023-03-19 19:00",
            temp_c: 25.2,
            temp_f: 77.4,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 13.6,
            wind_kph: 22.0,
            wind_degree: 268,
            wind_dir: "W",
            pressure_mb: 1008.0,
            pressure_in: 29.76,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 40,
            cloud: 5,
            feelslike_c: 25.5,
            feelslike_f: 77.9,
            windchill_c: 25.2,
            windchill_f: 77.4,
            heatindex_c: 25.5,
            heatindex_f: 77.9,
            dewpoint_c: 10.5,
            dewpoint_f: 50.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 15.7,
            gust_kph: 25.2,
            uv: 1.0,
          },
          {
            time_epoch: 1679236200,
            time: "2023-03-19 20:00",
            temp_c: 23.5,
            temp_f: 74.3,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 11.9,
            wind_kph: 19.1,
            wind_degree: 270,
            wind_dir: "W",
            pressure_mb: 1009.0,
            pressure_in: 29.8,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 44,
            cloud: 3,
            feelslike_c: 24.7,
            feelslike_f: 76.5,
            windchill_c: 23.5,
            windchill_f: 74.3,
            heatindex_c: 24.7,
            heatindex_f: 76.5,
            dewpoint_c: 10.7,
            dewpoint_f: 51.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 14.3,
            gust_kph: 23.0,
            uv: 1.0,
          },
          {
            time_epoch: 1679239800,
            time: "2023-03-19 21:00",
            temp_c: 22.4,
            temp_f: 72.3,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 11.0,
            wind_kph: 17.6,
            wind_degree: 270,
            wind_dir: "W",
            pressure_mb: 1010.0,
            pressure_in: 29.83,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 53,
            cloud: 0,
            feelslike_c: 24.6,
            feelslike_f: 76.3,
            windchill_c: 22.4,
            windchill_f: 72.3,
            heatindex_c: 24.6,
            heatindex_f: 76.3,
            dewpoint_c: 12.4,
            dewpoint_f: 54.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 13.2,
            gust_kph: 21.2,
            uv: 1.0,
          },
          {
            time_epoch: 1679243400,
            time: "2023-03-19 22:00",
            temp_c: 21.5,
            temp_f: 70.7,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 10.5,
            wind_kph: 16.9,
            wind_degree: 270,
            wind_dir: "W",
            pressure_mb: 1011.0,
            pressure_in: 29.84,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 63,
            cloud: 0,
            feelslike_c: 21.5,
            feelslike_f: 70.7,
            windchill_c: 21.5,
            windchill_f: 70.7,
            heatindex_c: 24.5,
            heatindex_f: 76.1,
            dewpoint_c: 14.2,
            dewpoint_f: 57.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 12.5,
            gust_kph: 20.2,
            uv: 1.0,
          },
          {
            time_epoch: 1679247000,
            time: "2023-03-19 23:00",
            temp_c: 20.7,
            temp_f: 69.3,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 9.4,
            wind_kph: 15.1,
            wind_degree: 271,
            wind_dir: "W",
            pressure_mb: 1011.0,
            pressure_in: 29.84,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 72,
            cloud: 0,
            feelslike_c: 20.7,
            feelslike_f: 69.3,
            windchill_c: 20.7,
            windchill_f: 69.3,
            heatindex_c: 20.7,
            heatindex_f: 69.3,
            dewpoint_c: 15.5,
            dewpoint_f: 59.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 11.6,
            gust_kph: 18.7,
            uv: 1.0,
          },
        ],
      },
    ],
  },
};


export default data;